### ISSUE TITLE
kdenlive doesnt work

### ISSUE THREAD

**Issue by nyancat18** [chiraag-nataraj/firejail-profiles#12]
https://gist.github.com/triceratops1/f34c1b68e535b2c35484810a38a14a70

**Comment by chiraag-nataraj** [comment]
Huh…that's weird. What is mprotect?

**Comment by triceratops1** [comment]
it appears be a grsec feature
but i dont use grsec
Linux *** 4.9.9-1

**Comment by triceratops1** [comment]
pd kdenlive works with this weird settings

firejail --noprofile --net=none kdenlive

**Comment by chiraag-nataraj** [comment]
Right, so that just means that `net none` isn't the problem.

**Comment by chiraag-nataraj** [comment]
Huh interesting...still works on my end. Which versions of kdenlive and firejail are you using?

**Comment by triceratops1** [comment]
kdenlive 16.12.2-1 (kde-applications kdemultimedia) [installed]
firejail version 0.9.44.8

**Comment by chiraag-nataraj** [comment]
Hmmm...okay, I have exactly the same versions and I'm not getting that error. Can you try commenting each line out one by one and see which one triggers the error?

**Comment by chiraag-nataraj** [comment]
Any updates on this? I'd love to fix the profile, but it's difficult if I can't replicate the issue.

**Comment by triceratops1** [comment]
i'm testing :D  



i gonna give you the result :P

**Comment by triceratops1** [comment]
i've troubles with kdenlive profile 
I'VE GAPPED ALL
but blender works without private-bin private-dev
and private-etc

**Comment by triceratops1** [comment]
cinelerra works   (as march2017)
synfigstudio (as1.2.0 WORKS FINE)
Natron (2.2.5) works fine

i'm testing brackets (1.9)

**Comment by chiraag-nataraj** [comment]
So what you seem to be saying is that your setup is significantly different from mine 😉
Okay, let's keep these in different issues.
For `kdenlive` (this thread), what you seem to be saying is that even when you comment out `private-bin` `private-dev`, `private-etc,` `shell none`, `seccomp`, `caps.drop all`, `noroot`, `nogroups`, and `ipc-namespace`, you still can't get `kdenlive` to start properly.
Two things:
* As you (perhaps) did not notice, you did not comment out the `private-tmp` part of this (which whitelists two things in `/tmp`). Comment that out and see if that resolves the issue.
* If that doesn't, then the issue is with the whitelists for the home directory or the blacklists on the system directories. Is your kdenlive installed in `/opt` by any chance?

For `blender`, please open a new issue so that we can discuss it in its own thread.

**Comment by triceratops1** [comment]
i've commented these lines
but doesnt work  


and my kdenlive its "normal" :D

**Comment by chiraag-nataraj** [comment]
So you say 😉
Okay, so you commented out all the `private-*` things. This means that the whitelists are the problem. Can you try commenting out all the whitelist and blacklist options and seeing if it will start?

**Comment by triceratops1** [comment]
ok

**Comment by triceratops1** [comment]
i've commented ALL except
net none



and works

**Comment by triceratops1** [comment]
https://paste.teknik.io/Raw/bO0Lw

**Comment by chiraag-nataraj** [comment]
Okay now _uncomment_ everything except for the blacklist and whitelist commands and see if it works (it should).

**Comment by triceratops1** [comment]
works too

**Comment by chiraag-nataraj** [comment]
Okay, so it's the whitelists. Good. That means that your `kdenlive` needs access to some additional config files (or something) that mine does not. Can you uncomment only the ones referring to the home directory to see if it still starts?

**Comment by chiraag-nataraj** [comment]
@nyancat18 lemme know which whitelists you can uncomment and still have it work :smile:

**Comment by nyancat18** [comment]
the home lines :)

we could give a harden dbus

and cut internet

**Comment by chiraag-nataraj** [comment]
I already cut internet to kdenlive, so that's not really an issue? I guess I can comment out the home lines for now with a note that they apparently break for some people 😄

**Comment by nyancat18** [comment]
thanks



home lines commented

and block internet (if the video its "poisoned" its fine) :dagger:
