### ISSUE TITLE
Libreoffice can not open documents on removable media

### ISSUE THREAD

**Issue by St0ner1995** [chiraag-nataraj/firejail-profiles#24]
is there a reason /media is blacklisted?

would it be possible to whitelist just /media/${USER}

**Comment by chiraag-nataraj** [comment]
I usually block `/media/` (and `/mnt`) because that's just another vector by which you can inject unsavory files. I'm not sure if `$USER` is supported as a variable (you'd have to ask @netblue30 over on the firejail repo) - if it is, that would probably work as a compromise 😉

**Comment by chiraag-nataraj** [comment]
I'm going to go ahead and close this, since removable media is very often a security risk (unknown files of unknown integrity, etc). As far as I know, `$USER` is not a variable (yet) in `firejail`, so I would advise keeping `disable-mnt` (in `common.inc`) and copying the files you want to the designated shared directories (in this case, `$HOME/Downloads`).
